spring:
  datasource:
    url: jdbc:postgresql://localhost:4008/history
    username: postgres
    password: postgres
  devtools:
    restart:
      poll-interval: 2s
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect 
    
  sql:
    init:
      mode: always
  rabbitmq:
    host: localhost
    port: 4006
    username: guest
    password: guest
  